//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VersatileMediaManager.PvrManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VersatileMediaManager.PvrManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @AddTimerPopupTimerChannel ähnelt.
        /// </summary>
        internal static string AddTimerPopupTimerChannel {
            get {
                return ResourceManager.GetString("AddTimerPopupTimerChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @AddTimerPopupTimerDescription ähnelt.
        /// </summary>
        internal static string AddTimerPopupTimerDescription {
            get {
                return ResourceManager.GetString("AddTimerPopupTimerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @AddTimerPopupTimerName ähnelt.
        /// </summary>
        internal static string AddTimerPopupTimerName {
            get {
                return ResourceManager.GetString("AddTimerPopupTimerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DeviceInfoCardDeviceName ähnelt.
        /// </summary>
        internal static string DeviceInfoCardDeviceName {
            get {
                return ResourceManager.GetString("DeviceInfoCardDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DeviceInfoCardEnigmaVersion ähnelt.
        /// </summary>
        internal static string DeviceInfoCardEnigmaVersion {
            get {
                return ResourceManager.GetString("DeviceInfoCardEnigmaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DeviceInfoCardHdd ähnelt.
        /// </summary>
        internal static string DeviceInfoCardHdd {
            get {
                return ResourceManager.GetString("DeviceInfoCardHdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DeviceInfoCardImageVersion ähnelt.
        /// </summary>
        internal static string DeviceInfoCardImageVersion {
            get {
                return ResourceManager.GetString("DeviceInfoCardImageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DeviceInfoCardInformation ähnelt.
        /// </summary>
        internal static string DeviceInfoCardInformation {
            get {
                return ResourceManager.GetString("DeviceInfoCardInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DeviceInfoCardTuner ähnelt.
        /// </summary>
        internal static string DeviceInfoCardTuner {
            get {
                return ResourceManager.GetString("DeviceInfoCardTuner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @DeviceInfoCardWebIfVersion ähnelt.
        /// </summary>
        internal static string DeviceInfoCardWebIfVersion {
            get {
                return ResourceManager.GetString("DeviceInfoCardWebIfVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @PvrManagementFlyoutHeader ähnelt.
        /// </summary>
        internal static string PvrManagementFlyoutHeader {
            get {
                return ResourceManager.GetString("PvrManagementFlyoutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @PvrManagementHomeHeader ähnelt.
        /// </summary>
        internal static string PvrManagementHomeHeader {
            get {
                return ResourceManager.GetString("PvrManagementHomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @TimerListCardTimerListHeader ähnelt.
        /// </summary>
        internal static string TimerListCardTimerListHeader {
            get {
                return ResourceManager.GetString("TimerListCardTimerListHeader", resourceCulture);
            }
        }
    }
}
