//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VersatileMediaManager.ConnectionManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VersatileMediaManager.ConnectionManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionManagementAddConnectionCancel ähnelt.
        /// </summary>
        internal static string ConnectionManagementAddConnectionCancel {
            get {
                return ResourceManager.GetString("ConnectionManagementAddConnectionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionManagementAddConnectionPopopTitle ähnelt.
        /// </summary>
        internal static string ConnectionManagementAddConnectionPopopTitle {
            get {
                return ResourceManager.GetString("ConnectionManagementAddConnectionPopopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionManagementConnectionAddedFailedStatusBarMessage ähnelt.
        /// </summary>
        internal static string ConnectionManagementConnectionAddedFailedStatusBarMessage {
            get {
                return ResourceManager.GetString("ConnectionManagementConnectionAddedFailedStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionManagementConnectionAddedStatusBarMessage ähnelt.
        /// </summary>
        internal static string ConnectionManagementConnectionAddedSuccessfullStatusBarMessage {
            get {
                return ResourceManager.GetString("ConnectionManagementConnectionAddedSuccessfullStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionManagementConnectionDeletedFailedStatusBarMessage ähnelt.
        /// </summary>
        internal static string ConnectionManagementConnectionDeletedFailedStatusBarMessage {
            get {
                return ResourceManager.GetString("ConnectionManagementConnectionDeletedFailedStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionManagementConnectionDeletedStatusBarMessage ähnelt.
        /// </summary>
        internal static string ConnectionManagementConnectionDeletedSuccessfullStatusBarMessage {
            get {
                return ResourceManager.GetString("ConnectionManagementConnectionDeletedSuccessfullStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionManagementConnectionHost ähnelt.
        /// </summary>
        internal static string ConnectionManagementConnectionHost {
            get {
                return ResourceManager.GetString("ConnectionManagementConnectionHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionManagementConnectionKind ähnelt.
        /// </summary>
        internal static string ConnectionManagementConnectionKind {
            get {
                return ResourceManager.GetString("ConnectionManagementConnectionKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionManagementConnectionName ähnelt.
        /// </summary>
        internal static string ConnectionManagementConnectionName {
            get {
                return ResourceManager.GetString("ConnectionManagementConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionManagementConnectionPassword ähnelt.
        /// </summary>
        internal static string ConnectionManagementConnectionPassword {
            get {
                return ResourceManager.GetString("ConnectionManagementConnectionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionManagementConnectionPort ähnelt.
        /// </summary>
        internal static string ConnectionManagementConnectionPort {
            get {
                return ResourceManager.GetString("ConnectionManagementConnectionPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionManagementConnectionTimeout ähnelt.
        /// </summary>
        internal static string ConnectionManagementConnectionTimeout {
            get {
                return ResourceManager.GetString("ConnectionManagementConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionManagementConnectionType ähnelt.
        /// </summary>
        internal static string ConnectionManagementConnectionType {
            get {
                return ResourceManager.GetString("ConnectionManagementConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionManagementConnectionUsername ähnelt.
        /// </summary>
        internal static string ConnectionManagementConnectionUsername {
            get {
                return ResourceManager.GetString("ConnectionManagementConnectionUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionManagementAddButtonText ähnelt.
        /// </summary>
        internal static string ConnectionManagementFlyoutAddButtonText {
            get {
                return ResourceManager.GetString("ConnectionManagementFlyoutAddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionManagementFlyoutDeleteButtonText ähnelt.
        /// </summary>
        internal static string ConnectionManagementFlyoutDeleteButtonText {
            get {
                return ResourceManager.GetString("ConnectionManagementFlyoutDeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionManagementFlyoutHeader ähnelt.
        /// </summary>
        internal static string ConnectionManagementFlyoutHeader {
            get {
                return ResourceManager.GetString("ConnectionManagementFlyoutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die @ConnectionManagementHomeHeader ähnelt.
        /// </summary>
        internal static string ConnectionManagementHomeHeader {
            get {
                return ResourceManager.GetString("ConnectionManagementHomeHeader", resourceCulture);
            }
        }
    }
}
